---

- name: baixando kafka no servidor
  unarchive:
    src: "{{ _kafka_link }}"
    dest: "/opt/"
    owner: "{{ user_kafka }}"
    creates: "/opt/kafka_{{ version_kafka_release }}-{{ version_kafka }}"
    remote_src: true
  become: true

- name: criando um link simbolico do kafka no path {{ path_kafka }}
  file:
    src: "/opt/kafka_{{ version_kafka_release }}-{{ version_kafka }}"
    dest: "{{ path_kafka }}"
    state: link
  become: true

- name: alterando o arquivo server.properties
  template:
    src: server.properties.j2
    dest: "{{ path_kafka }}/config/server.properties"
    owner: "{{ user_kafka }}"
    backup: true
  become: true

- name: alterando o arquivo zookeeper.properties
  template:
    src: zookeeper.properties.j2
    dest: "{{ path_kafka }}/config/zookeeper.properties"
    owner: "{{ user_kafka }}"
    backup: true
  become: true

- name: baixando a lib do prometheus
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.6/jmx_prometheus_javaagent-0.6.jar
    dest: /etc/kafka/libs/jmx_prometheus_javaagent-0.6.jar
    owner: "{{ user_kafka }}"
    mode: 0644
  become: true

- name: baixando o arquivo de metricas
  get_url:
    url: https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/kafka-0-8-2.yml
    dest: /etc/kafka/kafka-0-8-2.yml
    owner: "{{ user_kafka }}"
    mode: 0644
  become: true

- name: copiando o arquivo service
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
  notify:
    - inicia kafka
  become: true
